apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: idp-dev
# namespace: demo-postgres-idp_training-dev

resources:
  - service.yaml
  - deploy.yaml

images:
  # ATENTION name = image.name NOT name = spec.containers[0].name
  - name: ghcr.io/xidp/demo-postgres
    newTag: v0.1.0
